### ISSUE TITLE
Removed citing from readme

### ISSUE THREAD

**Issue by saoirse-iontach** [zen-fs/core#36]
Thanks for rebranding.

But even if current code base has significantly changed,
it keep inheriting from original work of John Vilk and Emery D. Berger.
So you should keep these two small citations.

(This apply to all ZenFS packages)

You only need the first paragraph with links:
```
### Citing
ZenFS is a fork of [BrowserFS](https://github.com/jvilk)
which was a component of the [Doppio](http://doppiojvm.org/)
and [Browsix](https://browsix.org/) research projects
from the PLASMA lab at the University of Massachusetts Amherst.

If you decide to use ZenFS/BrowserFS in a project that leads to a publication,
please cite the academic papers
on [Doppio](https://dl.acm.org/citation.cfm?doid=2594291.2594293)
and [Browsix](https://dl.acm.org/citation.cfm?id=3037727)
```

Maybe keeping also the summary:
```
### License
ZenFS and BrowserFS are licensed under the MIT License. See `LICENSE` for details.
```

About cleaning npm registry, one package left public: `@browserfs/fs-dom`

**Comment by dr-vortex** [comment]
@saoirse-iontach,

#### Concerning the Github issue:

> About cleaning npm registry, one package left public: `@browserfs/fs-dom`

I've made sure all of the `@browserfs` packages have the correct deprecation message.
> Maybe keeping also the summary:
> ```
> ### License
> ZenFS and BrowserFS are licensed under the MIT License. See `LICENSE` for details.
> ```

ZenFS is not required to mention BrowserFS in its license, since the MIT license is used.

Mentioning the license in the readme isn't necessary, since there is a license tab next to "readme" on Github:

<img src="https://github.com/zen-fs/core/assets/75621402/2c339d4b-8477-497c-9ef0-cf69201faf56" width="100px" />

> But even if current code base has significantly changed,
it keep inheriting from original work of John Vilk and Emery D. Berger.
So you should keep these two small citations.

ZenFS is not a research project nor a publication, so it does not need to include the citations. However, if any research projects use ZenFS then they may choose to include the citations from BrowserFS.

Notice that I have not removed citations from [jvilk/BrowserFS](https://github.com/jvilk/browserfs)'s readme.

#### Concerning some remarks you make in the readme of [saoirse-iontach/browser-fs-core](https://github.com/saoirse-iontach/browser-fs-core):

> As of April 2024, it is still in development, that's to say instable and not properly working (expectially encodings, with bad tests).

The current ZenFS API is stable, and everything (including the encoding/decoding) follows the NodeJS API exactly.

> More over contributors are actually dismissed.

This is not the case. ***You*** were blocked from [browser-fs](https://github.com/browser-fs) for using **derogatory and profane language**. Github is a professional platform, and should used as such. This corresponds with professional behavior, which you have **not** exhibited.

I would welcome future contributions you make provided they follow all of Github's policies as well as being professional in manner.

> **@BrowserFS** is [transient](//github.com/browser-fs/NOTICE) project from **BrowserFS** towards **@ZenFS**, (illegitimatly?) claiming to be the next **BrowserFS** (in fact it is **@ZenFS** before rebranding)

I am a legitimate and offical maintainer of [jvilk/BrowserFS](https://jvilk/BrowserFS). You can verify this by looking at the commit history, and noticing that I have write access to the repository. If that is not enough, feel free to reach out to Emery Berger, who can verify that.
 
> _dr-Vortex_ is an alias of _[[redacted]]_

While I may decide to release personal information, that right does not extend to you. Please remove my personal information (i.e. name) from all of your projects. This is not a request, it is a requirement under Github's [Acceptable Use  Policy, paragraph 3 section 4](https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies#3-intellectual-property-authenticity-and-private-information).

#### Concerning changes you have made to `package.json`:

You have changed the `author` field for forks of ZenFS packages to John Vilk. Dr. Vilk is the author of *BrowserFS*, **not** ZenFS. With all due respect, he is not a member of the ZenFS organization, and is not a contributor to ZenFS *as a fork*. This means that while he created *BrowserFS*, he has not made any contributions to *ZenFS* since the fork from BrowserFS was made.

Please correct this inaccuracy in your project. You can do this either by

A. Making a commit to the repositories which change the files [saoirse-iontach/browser-fs-core:package.json](https://github.com/saoirse-iontach/browser-fs-core/blob/main/package.json) and [saoirse-iontach/browser-fs-dom:package.json](https://github.com/saoirse-iontach/browser-fs-dom/blob/main/package.json).

B. Recreating your forks from [jvilk/BrowserFS](github.com/jvilk/BrowserFS) instead of ZenFS repositories.

Again, this is not a request, it is a requirement under Github's [Misinformation and Disinformation](https://docs.github.com/en/site-policy/acceptable-use-policies/github-misinformation-and-disinformation) policy.
