### ISSUE TITLE
Why is Node v22 needed?

### ISSUE THREAD

**Issue by ExpandOcean** [zen-fs/core#88]
Hello, the engine requires Node.js version 22 or higher. Is there a specific feature that needs this? The current default LTS version of Node.js is 20.

**Comment by james-pre** [comment]
@ExpandOcean,

Thanks for the question.

As mentioned in the [0.14.0 release notes](https://github.com/zen-fs/core/releases/tag/v0.14.0), the change to need Node v22 is for [`Promise.withResolvers`](https://mdn.io/Promise.withResolvers). If you polyfill `Promise.withResolvers` you should be able to use a lower Node version. 

I think it may be a good idea to add the polyfill in ZenFS since it is tribal and would save this headache. Especially since the engine field of the NPM package wouldn't need to be 22 then.

Just to show how easy the polyfill is:
```ts
Promise.withResolvers ??= function<T>(): PromiseWithResolvers<T> {
    let resolve, reject;
    const promise = new Promise((_resolve, _reject) => {
        resolve = _resolve;
        reject = _reject;
    });
    return { promise, resolve, reject };
}
```

The TS lib types from [ESNext.Promise](https://github.com/bloomberg/TypeScript/blob/580b87196780bc6e693107434144b90c378dd32c/src/lib/esnext.promise.d.ts) would also need to be included.
